name: Android Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Write local.properties (API keys)
        run: |
          cat > local.properties <<'EOF'
          OWM_API_KEY=${{ secrets.OWM_API_KEY }}
          # MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}
          EOF

      - name: Decode signing keystore
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 -d > signing.keystore

      - name: Build release bundle
        env:
          SIGNING_STORE_FILE: signing.keystore
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          ./gradlew --stacktrace --no-daemon :app:bundleRelease

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app/build/outputs/bundle/release/*.aab
