name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Write local.properties (API keys, etc.)
        run: |
          cat > local.properties <<'EOF'
          OWM_API_KEY=${{ secrets.OWM_API_KEY }}
          # MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}
          EOF

      - name: Build + Unit tests + Lint
        run: |
          ./gradlew --stacktrace --no-daemon \
            clean \
            testDebugUnitTest \
            lintDebug \
            assembleDebug

      - name: Upload unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: |
            **/build/test-results/testDebugUnitTest/**
            **/build/reports/tests/testDebugUnitTest/**
          if-no-files-found: warn

      - name: Upload Lint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: |
            **/build/reports/lint-results-debug.html
            **/build/reports/lint-results-debug.xml
          if-no-files-found: warn

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
